site_name: SSE Documentation Example
nav:
    - Home: 'index.md'
    - User Guide:
      - Installation: compilation-and-installation.md
      - Getting Started: how-to.md
repo_url: https://github.com/timotheehornek/documentation-tools-repository

site_author: Timoth√©e Hornek
#edit_uri: tree/master/docs/.